// app/lib/types/supabase.ts

/**
 * Database types - usually generated by Supabase CLI
 * These match your actual database schema
 */

export interface Profile {
  id: string;
  email: string;
  name?: string;
  full_name?: string;
  avatar_url?: string;
  age?: number;
  gender?: "male" | "female" | "other";
  height?: number;
  weight?: number;
  experience_level?: "beginner" | "intermediate" | "advanced";
  primary_goal?:
    | "weight_loss"
    | "muscle_gain"
    | "general_fitness"
    | "endurance";
  role?: "user" | "admin" | "trainer";
  created_at: string;
  updated_at: string;
}

export interface UserPreferences {
  id: string;
  user_id: string;
  workout_duration?: number;
  workout_frequency?: number;
  preferred_time?: "morning" | "afternoon" | "evening";
  equipment?: string[];
  music_genre?: string;
  notifications?: boolean;
  language?: "he" | "en";
  theme?: "light" | "dark" | "auto";
  created_at: string;
  updated_at: string;
}

export interface UserStats {
  id: string;
  user_id: string;
  total_workouts: number;
  total_minutes: number;
  current_streak: number;
  longest_streak: number;
  favorite_exercises?: string[];
  last_workout?: string;
  created_at: string;
  updated_at: string;
}

export interface Workout {
  id: string;
  user_id: string;
  name: string;
  description?: string;
  type?: string;
  duration?: number;
  calories_burned?: number;
  status: "planned" | "in_progress" | "completed" | "skipped";
  scheduled_for?: string;
  started_at?: string;
  completed_at?: string;
  created_at: string;
  updated_at: string;
}

export interface Exercise {
  id: string;
  name: string;
  name_he?: string;
  category: string;
  muscle_group: string;
  equipment?: string;
  difficulty: "beginner" | "intermediate" | "advanced";
  instructions?: string;
  instructions_he?: string;
  image_url?: string;
  video_url?: string;
  is_public: boolean;
  created_by?: string;
  created_at: string;
  updated_at: string;
}

export interface WorkoutExercise {
  id: string;
  workout_id: string;
  exercise_id: string;
  order_index: number;
  sets_planned: number;
  reps_planned?: number;
  weight_planned?: number;
  duration_planned?: number;
  rest_seconds?: number;
  notes?: string;
  created_at: string;
  updated_at: string;
}

export interface WorkoutSet {
  id: string;
  workout_exercise_id: string;
  set_number: number;
  reps?: number;
  weight?: number;
  duration?: number;
  distance?: number;
  completed: boolean;
  completed_at?: string;
  created_at: string;
  updated_at: string;
}

export interface Plan {
  id: string;
  name: string;
  description?: string;
  created_by: string;
  is_public: boolean;
  difficulty: "beginner" | "intermediate" | "advanced";
  duration_weeks: number;
  goals?: string[];
  tags?: string[];
  created_at: string;
  updated_at: string;
}

export interface PersonalRecord {
  id: string;
  user_id: string;
  exercise_id: string;
  record_type: "max_weight" | "max_reps" | "max_duration" | "min_time";
  value: number;
  unit?: string;
  achieved_at: string;
  workout_id?: string;
  notes?: string;
  created_at: string;
  updated_at: string;
}

export interface Achievement {
  id: string;
  name: string;
  name_he?: string;
  description: string;
  description_he?: string;
  icon?: string;
  category: string;
  points: number;
  criteria: any; // JSON field
  created_at: string;
  updated_at: string;
}

export interface UserAchievement {
  id: string;
  user_id: string;
  achievement_id: string;
  unlocked_at: string;
  progress?: number;
  created_at: string;
  updated_at: string;
}
