// app/constants/demoUsers.ts
import { User } from "@/app/lib/types/user";

export const demoUsers: User[] = [
  {
    id: "demo-1",
    email: "beginner@demo.com",
    name: "דני המתחיל",
    avatarUrl: "https://i.pravatar.cc/150?img=1",
    role: "user",
    demographics: {
      age: 25,
      gender: "male",
      height: 175,
      weight: 75,
      experienceLevel: "beginner",
      primaryGoal: "weight_loss",
      fitnessActivities: ["gym", "running"],
    },
    preferences: {
      workoutDuration: 45,
      workoutFrequency: 3,
      preferredTime: "morning",
      equipment: ["dumbbells", "bands"],
      musicGenre: "pop",
      notifications: true,
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "demo-2",
    email: "advanced@demo.com",
    name: "שרה המתקדמת",
    avatarUrl: "https://i.pravatar.cc/150?img=2",
    role: "user",
    demographics: {
      age: 32,
      gender: "female",
      height: 165,
      weight: 60,
      experienceLevel: "advanced",
      primaryGoal: "muscle_gain",
      fitnessActivities: ["gym", "yoga", "crossfit"],
    },
    preferences: {
      workoutDuration: 60,
      workoutFrequency: 5,
      preferredTime: "evening",
      equipment: ["full_gym"],
      musicGenre: "electronic",
      notifications: true,
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "demo-3",
    email: "intermediate@demo.com",
    name: "יוסי הביניים",
    avatarUrl: "https://i.pravatar.cc/150?img=3",
    role: "user",
    demographics: {
      age: 28,
      gender: "male",
      height: 180,
      weight: 85,
      experienceLevel: "intermediate",
      primaryGoal: "general_fitness",
      fitnessActivities: ["gym", "swimming"],
    },
    preferences: {
      workoutDuration: 50,
      workoutFrequency: 4,
      preferredTime: "afternoon",
      equipment: ["barbell", "machines"],
      musicGenre: "rock",
      notifications: false,
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];
